"""Markdown report generator using Jinja2."""

from pathlib import Path
from typing import Optional
from jinja2 import Template

from .models import ReportData, ReportSection


class MarkdownGenerator:
    """Generate Markdown reports from ReportData."""

    def __init__(self, template_path: Optional[str] = None):
        """
        Initialize Markdown generator.

        Args:
            template_path: Optional path to custom Jinja2 template
        """
        self.template_path = template_path
        self.template = self._load_template()

    def _load_template(self) -> Template:
        """
        Load Jinja2 template.

        Returns:
            Template instance
        """
        if self.template_path and Path(self.template_path).exists():
            # Load custom template from file
            with open(self.template_path, 'r', encoding='utf-8') as f:
                template_str = f.read()
        else:
            # Use built-in template
            template_str = self._get_builtin_template()

        return Template(template_str)

    def _get_builtin_template(self) -> str:
        """Get built-in Markdown template."""
        return """# {{ report.title }}

**Detail Level:** {{ report.detail_level.value|upper }} |
{% if report.author %}**Author:** {{ report.author }} |{% endif %}
**Created:** {{ report.created_at[:10] }}

---

{% macro render_section(section) -%}
{{ '#' * section.level }} {{ section.title }}

{{ section.content }}

{% if section.subsections -%}
{% for subsection in section.subsections %}
{{ render_section(subsection) }}
{% endfor %}
{% endif %}
{%- endmacro %}

{% for section in report.sections %}
{{ render_section(section) }}
{% endfor %}

---

*Report generated by Git Deep Analyzer*
"""

    def generate(self, report: ReportData) -> str:
        """
        Generate Markdown report.

        Args:
            report: Report data

        Returns:
            Markdown string
        """
        return self.template.render(report=report)

    def _render_section(self, section: ReportSection) -> str:
        """
        Render section to Markdown (helper for recursive rendering).

        Args:
            section: Section to render

        Returns:
            Markdown string
        """
        # This is handled by Jinja2 macro in template
        return f"\n{section.content}\n"

    def save_to_file(self, report: ReportData, output_path: str) -> None:
        """
        Generate and save Markdown report to file.

        Args:
            report: Report data
            output_path: Path to output Markdown file
        """
        markdown = self.generate(report)

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(markdown)
